Fixing includes, adding missing TODO markers to koans, comments.
c-koans/c_koans pull request #10
Opened 2020-03-04 17:47 UTC by codecop

Hi, thank you for the koans. A great exercise to get into C. While working through them I fixed a bunch of small things: Fixing includes, adding missing TODO markers to koans, formatting comments. Enjoy

2020-03-06 05:36 UTC, nbbeeken requested changes
Hello :wave: thank you so much for your contribution! We really do appreciate you taking the time to share your fixes. I think everything is pretty good to go (especially some much needed fixes :rocket:) 
I caught a few includes that don't seem to be used listed below:

2020-03-06 05:36 UTC, nbbeeken commented on src/about_control_statements.c
> +#include <stdbool.h>
Unused include

2020-03-06 05:36 UTC, nbbeeken commented on src/about_io.c
> +#include <strings.h>
Unused include

2020-03-06 05:36 UTC, nbbeeken commented on src/about_malloc.c
> +#include <strings.h>
Unused include

2020-03-06 05:36 UTC, nbbeeken commented on src/about_structs.c
> +#include <string.h>
Unused include

2020-03-06 11:02 UTC, codecop commented
Curious. I added it because compiler was complaining. I will remove it of course.

2020-03-11 23:34 UTC, codecop commented
Hi, the unused includes have been removed with the last (new) commit.

2020-03-12 14:54 UTC, nbbeeken approved these changes

2020-03-12 14:55 UTC, nbbeeken commented
Thanks again for helping out 👍

2020-03-16 17:57 UTC, merged